[build]
command="npm run build && npm run start"
publish="out"
functions="dist-functions"

[[redirects]]
 from = "/login/*"
to="https://shop-mojtaba.netlify.app/:splat"
  status = 200
  force = true


[[redirects]]
  from = "/*"
  to = "/sex.html"
  status = 200


