[build]
command="npm run build && npm run start"
publish="out"
functions="dist-functions"

[[redirects]]
 from = "/api/*"
to="https://shop-mojtaba.netlify.app/:splat"
  status = 200
  force = true


[[redirects]]
  from = "/api"
  to = "/sex.html"
  status = 200

[[headers]]
Access-Control-Allow-Origin: "*"
