[build]
command="npm run build && npm run start"
publish="out"
functions="dist-functions"

[[redirects]]
from="/"
to="/404"
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"



