[build]
command="npm run build && npm run start"
publish="out"
functions="dist-functions"

[[redirects]]
from="/*"
to="https://shop-mojtaba.netlify.app/.netlify/functions/mydata"
 
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"



